package Items;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Barrel.java
//  @ Date : 2020. 03. 26.
//  @ Author : 
//
//




public class Barrel extends GunPart implements Item {
}
