package Items;
import Player;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Item.java
//  @ Date : 2020. 03. 26.
//  @ Author : 
//
//




public abstract class Item {
	public void use(Player p) {
	}
	
	public boolean throw(Field f) {
	}
	
	public void pickUp() {
	}
}
