package Items;
import Player.Player;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Rope.java
//  @ Date : 2020. 03. 26.
//  @ Author : 
//
//




public class Rope extends Throwable implements Item {
	public void use(Player p) {
	}
}
