package Map;
import Player.Player;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Hole.java
//  @ Date : 2020. 03. 26.
//  @ Author : 
//
//




public class Hole extends Field {
	public void acceptPlayer(Player p) {
	}
	
	public void acceptPlayer(Player p) {
	}
}
