package Map;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Map.java
//  @ Date : 2020. 03. 26.
//  @ Author : 
//
//




public class Map {
	private Field fields;
	private void initFields() {
	}
	
	public void callBlizzardOnFields() {
	}
}
