package Player;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Scientist.java
//  @ Date : 2020. 03. 26.
//  @ Author : 
//
//




public class Scientist extends Player {
	private void doSkill() {
	}
	
	private void doSkill() {
	}
}
