//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Eskimo.java
//  @ Date : 2020. 03. 26.
//  @ Author : 
//
//




public class Eskimo extends Player {
	private boolean builtIgloo;
	private void doSkill() {
	}
	
	private void doSkill() {
	}
}
