import Map.Field;
import Map.Map;
import Player.Player;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Game.java
//  @ Date : 2020. 03. 26.
//  @ Author : 
//
//




public class Game {
	private int roundNum;
	private int roundsUntilBlizzard;
	private static int foundGunParts;
	private Map map;
	private Player players;
	private GameState state;
	public void doRound() {
	}
	
	public void callBlizzard() {
	}
	
	public static void winGame(Field f) {
	}
	
	public static void loseGame() {
	}
	
	public static void incGunParts() {
	}
}
