import Items.Item;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IceField.java
//  @ Date : 2020. 03. 26.
//  @ Author : 
//
//




public class IceField extends Field {
	private boolean iglooOnField;
	private Item frozenItem;
	private Item itemOnGround;
	public void acceptPlayer(Player p) {
	}
	
	public void acceptItem(Item i) {
	}
	
	public Item pickUpItem(Player p) {
	}
	
	public boolean digSnow(int amount) {
	}
	
	public void removeItemFromIce(Player p) {
	}
	
	public void acceptPlayer(Player p) {
	}
}
