//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Player.java
//  @ Date : 2020. 03. 26.
//  @ Author : 
//
//




public abstract class Player {
	private String name;
	private int health;
	private int stamina;
	private boolean isDrowning;
	private boolean dSuitOn;
	private Map players;
	private Field field;
	private Item inventory;
	private abstract void doSkill();
	private void openInventory() {
	}
	
	public void doTurn() {
	}
	
	public void changeSuit(DivingSuit dsuit) {
	}
	
	public void alterHealth(int n) {
	}
	
	public void drainStamina() {
	}
}
