//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pos.java
//  @ Date : 2020. 03. 26.
//  @ Author : 
//
//




public class Pos {
	private int x;
	private int y;
}
