//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Throwable.java
//  @ Date : 2020. 03. 26.
//  @ Author : 
//
//




public abstract class Throwable implements Item, Item {
	public boolean throw(Field f) {
	}
	
	public void pickUp() {
	}
}
