//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : UnstableField.java
//  @ Date : 2020. 03. 26.
//  @ Author : 
//
//




public class UnstableField extends IceField {
	public void acceptPlayer(Player p) {
	}
}
